### ISSUE TITLE
AddressSanitizer: SEGV on unknown address 0x00000000 

### ISSUE THREAD

**Issue by fmunozs** [ali-rantakari/peg-markdown-highlight#10]
Attached test case generates an exception when highlighter is compiled with ASAN enabled, it was fuzzed with AFL. The backtrace makes me thing that a NULL is getting paased to strdup, but I've not checke any of the code.

```
~/markdown/peg-markdown-highlight# ./highlighter x.txt 
ASAN:SIGSEGV
=================================================================
==15348==ERROR: AddressSanitizer: SEGV on unknown address 0x00000000 (pc 0xb792b861 bp 0x00000000 sp 0xbffff1bc T0)
    #0 0xb792b860  (/lib/i386-linux-gnu/i686/cmov/libc.so.6+0x76860)
    #1 0xb792b51a in strdup (/lib/i386-linux-gnu/i686/cmov/libc.so.6+0x7651a)
    #2 0x806e216 in yy_1_Reference /root/markdown/peg-markdown-highlight/pmh_parser.c:1579
    #3 0x80f6805 in yyDone /root/markdown/peg-markdown-highlight/pmh_parser.c:1218
    #4 0x80f6805 in yyparse_from /root/markdown/peg-markdown-highlight/pmh_parser.c:6537
    #5 0x80f7f84 in _parse /root/markdown/peg-markdown-highlight/pmh_parser.c:6598
    #6 0x80f7f84 in parse_references /root/markdown/peg-markdown-highlight/pmh_parser.c:6616
    #7 0x80f7f84 in pmh_markdown_to_elements /root/markdown/peg-markdown-highlight/pmh_parser.c:526
    #8 0x8051ec7 in main /root/markdown/peg-markdown-highlight/highlighter.c:72
    #9 0xb78cd70d in __libc_start_main (/lib/i386-linux-gnu/i686/cmov/libc.so.6+0x1870d)
    #10 0x805210b  (/root/markdown/peg-markdown-highlight/highlighter+0x805210b)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 ??
==15348==ABORTING
```
[x.txt](https://github.com/ali-rantakari/peg-markdown-highlight/files/110284/x.txt)

**Comment by fmunozs** [comment]
For the record, using "]:0" only I get the same backtrace.

**Comment by ali-rantakari** [comment]
Thanks for the good bug report!
